### ISSUE TITLE
Add "Manual Installation" section to the Readme

### ISSUE THREAD

**Issue by kavalerov** [ably/ably-asset-tracking-cocoa#149]
Add Manual Installation section to the readme similar to https://github.com/ably/ably-cocoa#manual-installation

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-894) by [Unito](https://www.unito.io)

**Comment by ben-xD** [comment]
_I wrote the following this morning but found the tab still open without the comment sent:_

There are 2 issues I found:
- The manual installation section doesn't actually work from `ably-cocoa`. It refers to `ably-cocoa/ably-cocoa` which doesn't exist. 
- More importantly, getting a manual install to work for asset tracking is harder because:
  - Its an Xcode workspace involving a multiple Xcode projects of core, publisher SDK, subscriber SDK, cocoapods project (ably-cocoa is a Xcode project). Therefore, for a user to add these to their workspace, they need to build Core, Publisher and Subscriber, and add these as a dependency. 
  - If they don't use a workspace, then they have to start using one?
  - They have to know which files they are using, and explicitly add each one of them to their project.

Though its still possible to write the details for this manual installation, I think it's quite hacky. If we solve https://github.com/ably/ably-asset-tracking-cocoa/issues/154 , then this issue would be obsoleted, and adding SPM support would be much easier.
